### ISSUE TITLE
RDS EC2 연결

### ISSUE THREAD

**Issue by oro7l** [TEAM2-FORCE/force_be#37]
![image](https://github.com/TEAM2-FORCE/force_be/assets/127576762/c7a4ce29-97f5-4f02-9442-d7b8574e6542)
로컬과 mysql 연결은 잘되는데,,
rds랑 ec2 연결하려고만 하면 저런 오류가 뜹니다 ㅠㅠ 
보안그룹 인바인드 규칙, public access 다 확인했는데 이상없고 찾아보니 방화벽 문제라고 하는데 건드려도 괜찮을까요,,?
@na-yk @devrokket

**Comment by na-yk** [comment]
### 결과
**성공성공**🥳
<img width="715" alt="캡처" src="https://github.com/TEAM2-FORCE/force_be/assets/102007066/36b5e010-dc09-4fc1-9d44-8152b9ac91b6">

### 해결한 것들
- [X] `mysqlclient` 모듈 설치 오류
- [X] secrets.json DB 정보 업데이트(`DB_HOST`, `DB_PASSWORD`)
- [X] RDS가 사용하는 서브넷의 라우팅 테이블 수정
- [X] 데이터베이스 생성

### 해결 과정
@oro7l 가 `settings.py`, `requirements.txt`는 먼저 설정해 준 덕분에 아래의 것들만 수정했습니다!
#### 1️⃣  `mysqlclient` 모듈 설치 오류 해결
<details>
<summary>설치 과정에서 발생했던 오류</summary>
<div markdown="1">

```
# python -m pip install mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-2.2.0.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /bin/sh: 1: pkg-config: not found
      /bin/sh: 1: pkg-config: not found
      Trying pkg-config --exists mysqlclient
      Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
      Trying pkg-config --exists mariadb
      Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-6mxonive/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-6mxonive/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-6mxonive/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 154, in <module>
        File "<string>", line 48, in get_config_posix
        File "<string>", line 27, in find_package_name
      Exception: Can not find valid pkg-config name.
      Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```
</div>
</details>

`mysqlclient` 버전 2.2.0 설치부터 *pkg-config*가 필요하다는 뜻이라네요.  

출처는 [여기](https://www.sysnet.pe.kr/2/0/13377)

```
$ sudo apt install default-libmysqlclient-dev pkg-config -y
$ pip install -r requirements.txt
```

#### 2️⃣  `secrets.json` DB 정보 업데이트
배포 서버의 secrets.json에 `DB_HOST`와 `DB_PASSWORD`를 반영했습니다.  


#### 3️⃣ RDS가 사용하는 서브넷의 라우팅 테이블 수정
DataGrip으로 RDS의 DB에 접속을 하려는데.. Test Connection에서 `Connection timed out`이 발생하더라고요!
RDS가 사용하는 서브넷의 라우팅 테이블을 수정했습니다.
[이 블로그](https://gksdudrb922.tistory.com/240)를 참고했습니다.

#### 4️⃣ 데이터베이스 생성
DataGrip으로 RDS 데이터베이스에 접속해서 콘솔에 아래 명령어를 실행해서 데이터베이스를 생성했습니다.
```
create database vebe
```
